---
title: "Lads"
output: pdf_document
---

```{r setup,echo=F, message=FALSE, warning=FALSE}
library(rtracklayer) # for loading .bw files
library(data.table)
library(ggplot2)
    library(gridExtra)
library(dplyr)
library(stats)
library(mixtools)  # jesus all this for bimodal middle estimation.....
library(DNAcopy)
```

Comparison of Nup62KO integrations to Lads

```{r, echo = F}
#Load data
restbw <- import.bw("Jurkat Lamin DAmID RGSE94971_sq77.dpn_smooth_60_R.bw")
actbw <- import.bw("Jurkat Lamin Dam ID A GSE94971_sq77.dpn_smooth_60_A.bw")
df_rest <- as.data.frame(restbw)
df_act <- as.data.frame(actbw)
#Load Nup data as well
nups <- read.csv("C:/Users/38598/Desktop/hivint/nup153/Nup_62_2/Nup_all_peaks_together.csv")
nups <- nups[,-1]

# load the random integration data as well at some point
```

Note: DamID lads data is raw (only short outliers seem to be filtered out, with background left in). I re-called the peaks using the same method mentioned in the paper (circualr binary segmentation).

```{r, echo = F}
bin = 0.5

pr <- ggplot(df_rest, aes(x=score))+ geom_histogram(binwidth = bin, alpha = 0.4)+theme_minimal()+ggtitle("Resting Lamin DamID scores")+
   # geom_line(data = denr, aes(x = x, y = y *length(x) * bin),
   #         color = "blue")+
    geom_vline(xintercept=midpoint, col = "red")#+
    #geom_vline(xintercept=r_min[36], col = "blue")
pa <- ggplot(df_act, aes(x=score))+ geom_histogram(binwidth = bin, alpha = 0.4)+theme_minimal()+ggtitle("Activated Lamin DamID scores")+
    #geom_line(data = dena, aes(x = x, y *length(x) * bin),
    #        color = "blue")+
    geom_vline(xintercept=midpoint2, col = "red")#+
    #geom_vline(xintercept=a_min[2], col = "blue")#+
    #geom_vline(xintercept=a_min[3], col = "orange")

grid.arrange(pa, pr, ncol=2)
```

```{r, echo = F}
# tunning the DNA copy method
df_act <- as.data.table(df_act)
df_rest <- as.data.table(df_rest)

cna.object <- CNA(
  genomdat = df2$score,
  chrom    = df2$seqnames,
  maploc   = df2$mid,
  data.type= "logratio"
)
smoothed <- smooth.CNA(cna.object) # this does nothing since its already smooth i think

seg.results <- segment(
  smoothed,
  weights = df2$width,
  verbose = 1
)
segments.df <- seg.results$output
```

Example plot of score distribution on chromosomes and called LADs (by me)

```{r,echo = FALSE}

df2 <- df_act[seqnames %in% c("chr15"),]%>%
      mutate(mid = (start + end) / 2)
dfg <- segments.df[segments.df$seg.mean >=1,]
dfb <- segments.df[segments.df$seg.mean <=-2,]

ggplot(df2ยง, aes(x = mid, y = 0, xend = mid, yend = score)) +
 geom_segment(color = "steelblue", alpha = 0.6) +
 # segemnts that ae def not LADS
 geom_segment(
    data = dfb,
    aes(
      x    = loc.start,
      xend = loc.end,
      y    = - 4.3,     # lower the bar slightly
      yend = - 4.4      # same y for horizontal
    ),
    color = "darkred",
    size  = 2
 )+
    # probably lads?
 geom_segment(
data = dfg,
  aes(
        x  = loc.start,
        xend  = loc.end,
        y = -4.2,
       yend=-4.3),
       color = "green",size = 2) +
     facet_wrap(~ seqnames, scales = "free_x") +
    labs(x = "Genomic coordinate (bp)", y = "Score") +
    theme_minimal()+
    geom_point(
    aes(x = Inf, y = Inf, color = "Raw score"),
    show.legend = TRUE
  ) +
  geom_point(
    aes(x = Inf, y = Inf, color = "LADs"),
    show.legend = TRUE
  ) +
    geom_point(
    aes(x = Inf, y = Inf, color = "Not LADs"),
    show.legend = TRUE
  ) +
scale_color_manual(
    name   = "",
    values = c(
      "Raw score"     = "steelblue",
      "LADs"  = "green",
      "Not LADs" = "darkred"
    )
  ) 
```

```{r}
dfg <- as.data.table(dfg)
dfb <- as.data.table(dfb)
setkey(dfb, loc.start,loc.end)
setkey(dfg, loc.start,loc.end)
foverlaps(dfb,dfg)  #so its just visual problem?
```
Exact overlaps for all Lads and all Nup62KO integrations

```{r}

```